### ISSUE TITLE
Missing angular-cli.json (or angular.json in 6+)

### ISSUE THREAD

**Issue by milesburton** [PacktPublishing/Hands-On-Data-Structures-and-Algorithms-with-JavaScript#1]
As title, none of the projects include this file so it's tricky to retrofit

**Comment by 40x** [comment]
Have you tried to update the package json of these projects to the latest angular dependencies (6+)? Once you do that and do an `npm install`, it will prompt the following:


================================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
================================================================================

and you can upgrade it from there. I will open a PR and fix the projects as soon as I can, for now can you try this and let me know if it does not work?

**Comment by rattanakchea** [comment]
I updated angular/cli and got the following error for `ng serve`
```
Could not determine a single project for the 'serve' target.
Error: Could not determine a single project for the 'serve' target.
```

**Comment by 40x** [comment]
@rattanakchea have you look at (and followed the steps) listed in https://update.angular.io/ ? This is all you need to effectively upgrade. If that does not work, create a sample project and share the link and I can take a look at it as well.
